(function(){
  "use strict";
  var cache=null, active="aging", season="2026";
  function e(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
  function f(v,d){var n=Number(v);return Number.isFinite(n)?n.toFixed(d==null?3:d):"-";}
  function n(v){return Number(v)||0;}
  function opts(values,current,all){return (all?[all]:[]).concat(values).map(function(v){return '<option'+(v===current?' selected':'')+'>'+e(v)+'</option>';}).join("");}
  function uniq(rows,key){return Array.from(new Set(rows.map(function(x){return x[key];}).filter(Boolean))).sort(function(a,b){return String(a).localeCompare(String(b),"ja",{numeric:true});});}
  function metricCard(label,value,sub){return '<div class="al-kpi"><strong>'+e(value)+'</strong><span>'+e(label)+(sub?' · '+e(sub):'')+'</span></div>';}
  function lineChart(rows,xKey,yKey,label,lowerBetter){
    if(!rows||!rows.length)return '<div class="al-empty">表示できる標本がありません</div>';
    var W=700,H=270,p={l:48,r:18,t:20,b:42},xs=rows.map(function(r){return n(r[xKey]);}),ys=rows.map(function(r){return n(r[yKey]);});
    var xmin=Math.min.apply(null,xs),xmax=Math.max.apply(null,xs),ymin=Math.min.apply(null,ys),ymax=Math.max.apply(null,ys); if(ymin===ymax){ymin-=1;ymax+=1;}
    var X=function(v){return p.l+(v-xmin)/(xmax-xmin||1)*(W-p.l-p.r);},Y=function(v){return p.t+(ymax-v)/(ymax-ymin)*(H-p.t-p.b);};
    var points=rows.map(function(r){return X(n(r[xKey])).toFixed(1)+','+Y(n(r[yKey])).toFixed(1);}).join(' ');
    var grid=[0,.25,.5,.75,1].map(function(q){var yy=p.t+q*(H-p.t-p.b),val=ymax-q*(ymax-ymin);return '<line class="grid" x1="'+p.l+'" y1="'+yy+'" x2="'+(W-p.r)+'" y2="'+yy+'"/><text x="4" y="'+(yy+4)+'">'+f(val,yKey==='era'?2:3)+'</text>';}).join('');
    var dots=rows.map(function(r){return '<circle class="dot" cx="'+X(n(r[xKey]))+'" cy="'+Y(n(r[yKey]))+'" r="4"><title>'+e(r[xKey])+'歳 '+e(label)+' '+f(r[yKey],yKey==='era'?2:3)+' / '+e(r.players||'')+'人</title></circle>';}).join('');
    return '<svg class="al-chart" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="'+e(label)+'の年齢曲線"><defs><linearGradient id="alGradient" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#ed570b"/><stop offset="1" stop-color="#fff"/></linearGradient></defs>'+grid+'<polyline class="line" points="'+points+'"/>'+dots+'<text x="'+(W/2-35)+'" y="'+(H-8)+'">年齢（7月1日時点）</text><text x="'+(W-120)+'" y="15">'+(lowerBetter?'低いほど良い':'高いほど良い')+'</text></svg>';
  }
  function table(headers,rows){return '<div class="al-scroll"><table class="al-table stbl"><thead><tr>'+headers.map(function(h){return '<th>'+e(h)+'</th>';}).join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>';}
  function tabs(){var items=[['aging','年齢曲線'],['value','RE24・WPA'],['conditions','条件分析'],['similar','類似選手'],['backtest','予測検証'],['quality','データ品質']];return '<div class="al-tabs">'+items.map(function(x){return '<button class="al-tab '+(active===x[0]?'on':'')+'" data-al-tab="'+x[0]+'">'+x[1]+'</button>';}).join('')+'</div>';}
  function renderAging(){var a=cache.aging||{},kind=sessionStorage.getItem('alAging')||'batting',rows=kind==='batting'?a.batting_curve:a.pitching_curve,y=kind==='batting'?'ops':'era';return '<div class="al-grid"><section class="al-card wide"><h3 class="al-title">NPB年齢曲線 <span class="al-pill">'+e(a.age_definition)+'</span></h3><div class="al-controls"><label>対象<select id="al-aging-kind"><option value="batting"'+(kind==='batting'?' selected':'')+'>野手 OPS</option><option value="pitching"'+(kind==='pitching'?' selected':'')+'>投手 ERA</option></select></label></div>'+lineChart(rows,'age',y,kind==='batting'?'OPS':'防御率',kind==='pitching')+'<p class="al-sub">各年齢は一定以上の出場量がある選手を、打席または投球回で加重平均。年齢による因果効果ではありません。</p></section><section class="al-card wide"><h3 class="al-title">年齢別標本</h3>'+table(['年齢','選手数',kind==='batting'?'打席':'投球回',kind==='batting'?'OPS':'防御率'],rows.map(function(r){return '<tr><td>'+r.age+'歳</td><td class="al-num">'+r.players+'</td><td class="al-num">'+e(r.pa||r.innings)+'</td><td class="al-num"><b>'+f(r[y],kind==='batting'?3:2)+'</b></td></tr>'; }))+'</section></div>';}
  function renderHeat(states){var bases=['---','1--','-2-','--3','12-','1-3','-23','123'],labels=['なし','一塁','二塁','三塁','一二塁','一三塁','二三塁','満塁'];var max=Math.max.apply(null,states.map(function(x){return n(x.expected_runs);}));var h='<div class="al-heat"><div class="hdr">アウト</div>'+labels.map(function(x){return '<div class="hdr">'+x+'</div>';}).join('');[0,1,2].forEach(function(o){h+='<div class="hdr">'+o+'死</div>';bases.forEach(function(b){var r=states.find(function(x){return x.outs===o&&x.bases===b;})||{};var q=max?n(r.expected_runs)/max:0;h+='<div class="cell" style="background:rgba(237,87,11,'+(.08+.55*q)+')"><b>'+f(r.expected_runs,3)+'</b><br><small>n='+n(r.sample).toLocaleString()+'</small></div>';});});return h+'</div>';}
  function leaders(rows,metric){return table(['#','選手','球団','打席',metric.toUpperCase()],(rows||[]).slice(0,15).map(function(r,i){return '<tr><td class="al-rank">'+(i+1)+'</td><td><b>'+e(r.name)+'</b></td><td>'+e(r.team)+'</td><td class="al-num">'+n(r.pa)+'</td><td class="al-num"><b>'+f(r[metric],metric==='wpa'?3:2)+'</b></td></tr>'; }));}
  function renderValue(){var re=cache.re24||{},wp=cache.wpa_est||{};return '<div class="al-grid"><section class="al-card wide"><h3 class="al-title">24塁状況別 得点期待値 <span class="al-pill">実測集計</span></h3><div class="al-scroll">'+renderHeat(re.states||[])+'</div><p class="al-sub">その状態からイニング終了までに入った平均得点。セルの n は観測打席数です。</p></section><section class="al-card"><h3 class="al-title">野手 RE24 上位</h3>'+leaders(re.batters,'re24')+'</section><section class="al-card"><h3 class="al-title">投手 RE24 上位</h3>'+leaders(re.pitchers,'re24')+'</section><section class="al-card"><h3 class="al-title">野手 推定WPA 上位</h3>'+leaders(wp.batters,'wpa')+'</section><section class="al-card"><h3 class="al-title">投手 推定WPA 上位</h3>'+leaders(wp.pitchers,'wpa')+'</section><section class="al-card wide al-note"><b>重要：</b> WPAは公式値ではありません。'+e(wp.model_prior||'当サイトの試合データによる推定')+'。RE24も打席途中の暴投等を取りこぼす可能性があります。</section></div>';}
  function rates(rows){var s={pa:0,ab:0,hit:0,single:0,double:0,triple:0,hr:0,bb:0,hbp:0,so:0,rbi:0};rows.forEach(function(r){Object.keys(s).forEach(function(k){s[k]+=n(r[k]);});});var avg=s.ab?s.hit/s.ab:null,obp=(s.ab+s.bb+s.hbp)?(s.hit+s.bb+s.hbp)/(s.ab+s.bb+s.hbp):null,slg=s.ab?(s.single+2*s.double+3*s.triple+4*s.hr)/s.ab:null;return {raw:s,avg:avg,obp:obp,slg:slg,ops:obp==null||slg==null?null:obp+slg,k:s.pa?s.so/s.pa:null,bb:s.pa?s.bb/s.pa:null};}
  function renderConditions(){var rows=cache.condition_cube||[],keys=[['team','球団'],['bat_hand','打者左右'],['pit_hand','投手左右'],['inning','回'],['runners','走者'],['outs','アウト'],['home_away','H/V']];var selected={};keys.forEach(function(x){selected[x[0]]=sessionStorage.getItem('alCond-'+x[0])||'すべて';});var match=rows.filter(function(r){return keys.every(function(x){return selected[x[0]]==='すべて'||r[x[0]]===selected[x[0]];});}),x=rates(match),sample=x.raw.pa,conf=sample>=500?'高':sample>=150?'中':sample>=50?'低':'参考';var controls=keys.map(function(k){return '<label>'+k[1]+'<select class="al-cond" data-key="'+k[0]+'">'+opts(uniq(rows,k[0]),selected[k[0]],'すべて')+'</select></label>';}).join('');return '<div class="al-grid"><section class="al-card wide"><h3 class="al-title">条件別打撃分析 <span class="al-pill">信頼度 '+conf+'</span></h3><div class="al-controls">'+controls+'</div><div class="al-kpis">'+metricCard('対象打席',sample.toLocaleString(),'セル'+match.length+'件')+metricCard('打率',f(x.avg,3))+metricCard('OPS',f(x.ops,3))+metricCard('三振率',x.k==null?'-':f(x.k*100,1)+'%')+'</div></section><section class="al-card"><h3 class="al-title">打撃内訳</h3>'+table(['安打','二塁打','三塁打','本塁打','四球','死球','打点'],['<tr>'+['hit','double','triple','hr','bb','hbp','rbi'].map(function(k){return '<td class="al-num">'+x.raw[k]+'</td>';}).join('')+'</tr>'])+'</section><section class="al-card"><h3 class="al-title">率指標</h3><div class="al-kpis">'+metricCard('AVG',f(x.avg,3))+metricCard('OBP',f(x.obp,3))+metricCard('SLG',f(x.slg,3))+metricCard('BB%',x.bb==null?'-':f(x.bb*100,1)+'%')+'</div><p class="al-sub">条件を重ねるほど標本は小さくなります。50打席未満は傾向ではなく参考値として扱ってください。</p></section></div>';}
  function renderSimilar(){var all=cache.similarity||{},kind=sessionStorage.getItem('alSimKind')||'batter',part=all[kind]||{players:[],fields:[]},saved=sessionStorage.getItem('alSimPlayer'),cur=part.players.find(function(x){return x.player_key===saved;})||part.players[0];var choices=part.players.slice().sort(function(a,b){return String(a.name).localeCompare(String(b.name),'ja');});var pairs=cur?cur.similar:[];return '<div class="al-grid"><section class="al-card wide"><h3 class="al-title">プレースタイル類似度 <span class="al-pill">標準化ユークリッド距離</span></h3><div class="al-controls"><label>種別<select id="al-sim-kind"><option value="batter"'+(kind==='batter'?' selected':'')+'>野手</option><option value="pitcher"'+(kind==='pitcher'?' selected':'')+'>投手</option></select></label><label>選手<select id="al-sim-player">'+choices.map(function(x){return '<option value="'+e(x.player_key)+'"'+(cur&&x.player_key===cur.player_key?' selected':'')+'>'+e(x.name)+'（'+e(x.team)+'）</option>';}).join('')+'</select></label></div><div class="al-note">比較項目：'+part.fields.map(e).join(' / ')+'。出場量が少ない選手は除外し、同一シーズンの傾向が近い選手を表示します。</div></section>'+pairs.map(function(x,i){return '<section class="al-card third"><div class="al-pair"><span class="al-rank">#'+(i+1)+'</span><span class="al-score">'+f(x.score,1)+'</span></div><h3>'+e(x.name)+'</h3><p class="al-sub">'+e(x.team)+' / 類似スコア（100に近いほど類似）</p></section>';}).join('')+'</div>';}
  function renderBacktest(){var b=cache.backtest||{},s=b.summary||{},br=(b.batters||[]).slice(0,15),pr=(b.pitchers||[]).slice(0,15);return '<div class="al-grid"><section class="al-card wide"><h3 class="al-title">時間順ホールドアウト検証 <span class="al-pill">境界 '+e(b.cutoff)+'</span></h3><div class="al-kpis">'+metricCard('野手 OPS MAE',f((s.batting_ops||{}).mae,3),(s.batting_ops||{}).players+'人')+metricCard('投手 ERA MAE',f((s.pitching_era||{}).mae,2),(s.pitching_era||{}).players+'人')+'</div><p class="al-sub">'+e(b.method)+'。MAEは予測と実績の絶対誤差平均で、小さいほど良好です。</p></section><section class="al-card"><h3 class="al-title">野手 OPS 予測誤差が小さい順</h3>'+table(['選手','学習PA','検証PA','予測','実績','誤差'],br.map(function(r){return '<tr><td>'+e(r.name)+'</td><td class="al-num">'+r.train_pa+'</td><td class="al-num">'+r.test_pa+'</td><td class="al-num">'+f(r.prediction,3)+'</td><td class="al-num">'+f(r.actual,3)+'</td><td class="al-num">'+f(r.error,3)+'</td></tr>'; }))+'</section><section class="al-card"><h3 class="al-title">投手 ERA 予測誤差が小さい順</h3>'+table(['選手','学習回','検証回','予測','実績','誤差'],pr.map(function(r){return '<tr><td>'+e(r.name)+'</td><td class="al-num">'+r.train_innings+'</td><td class="al-num">'+r.test_innings+'</td><td class="al-num">'+f(r.prediction,2)+'</td><td class="al-num">'+f(r.actual,2)+'</td><td class="al-num">'+f(r.error,2)+'</td></tr>'; }))+'</section></div>';}
  function renderQuality(){var q=cache.quality||{},counts=q.counts||{},cov=q.coverage_pct||{};function coverage(name,obj){return '<section class="al-card third"><h3 class="al-title">'+e(name)+'</h3>'+Object.keys(obj||{}).map(function(k){return '<div class="al-pair"><span>'+e(k)+'</span><span style="width:55%"><b>'+f(obj[k],1)+'%</b><div class="al-bar"><i style="width:'+Math.max(0,Math.min(100,n(obj[k])))+'%"></i></div></span></div>';}).join('')+'</section>'; }return '<div class="al-grid"><section class="al-card wide"><h3 class="al-title">データ監査 <span class="al-pill">'+e((q.range||{}).start)+'〜'+e((q.range||{}).end)+'</span></h3><div class="al-kpis">'+metricCard('試合',n(counts.games).toLocaleString())+metricCard('打席',n(counts.atbats).toLocaleString())+metricCard('投球',n(counts.pitches).toLocaleString())+metricCard('投手試合行',n(counts.pitching_lines).toLocaleString())+'</div></section>'+coverage('試合データ',cov.games)+coverage('打席データ',cov.atbats)+coverage('投球データ',cov.pitches)+'<section class="al-card wide"><h3 class="al-title">制約・注意点</h3>'+(q.warnings||[]).map(function(x){return '<div class="al-warning">'+e(x)+'</div>';}).join('')+'</section></div>';}
  function body(){return active==='aging'?renderAging():active==='value'?renderValue():active==='conditions'?renderConditions():active==='similar'?renderSimilar():active==='backtest'?renderBacktest():renderQuality();}
  function render(){var root=document.getElementById('analysisLabView');if(!root)return;root.innerHTML='<div class="section al-shell"><div class="al-head"><div><div class="al-kicker">NPB ANALYTICS LAB</div><h2>分析ラボ</h2><div class="al-sub">記述 → 比較 → 検証までを、標本数と限界付きで確認</div></div><div class="al-note">推定値は <b>推定</b> と明記し、取得できない情報は補完しません。</div></div>'+tabs()+body()+'</div>';bind();}
  function bind(){document.querySelectorAll('[data-al-tab]').forEach(function(b){b.onclick=function(){active=b.dataset.alTab;render();};});var a=document.getElementById('al-aging-kind');if(a)a.onchange=function(){sessionStorage.setItem('alAging',a.value);render();};document.querySelectorAll('.al-cond').forEach(function(x){x.onchange=function(){sessionStorage.setItem('alCond-'+x.dataset.key,x.value);render();};});var sk=document.getElementById('al-sim-kind');if(sk)sk.onchange=function(){sessionStorage.setItem('alSimKind',sk.value);sessionStorage.removeItem('alSimPlayer');render();};var sp=document.getElementById('al-sim-player');if(sp)sp.onchange=function(){sessionStorage.setItem('alSimPlayer',sp.value);render();};}
  window.loadAnalysisLab=async function(){var root=document.getElementById('analysisLabView');if(!root)return;if(cache){render();return;}root.innerHTML='<div class="section al-shell"><div class="al-empty">分析データを読み込み中…</div></div>';try{var y=(typeof dp!=='undefined'&&dp.value?dp.value.slice(0,4):season)||season;var res=await fetch('data/'+y+'/analysis_lab.json?t='+Date.now());if(!res.ok)throw new Error('HTTP '+res.status);cache=await res.json();season=cache.season||y;render();}catch(err){root.innerHTML='<div class="section al-shell"><div class="al-note"><b>分析データを読み込めませんでした。</b><br>'+e(err.message)+'<br>Actions の再集計後に利用できます。</div></div>';}};
  if(typeof curView!=="undefined"&&curView==="analysislab")window.loadAnalysisLab();
})();
