(function(){
  "use strict";
  var data=null,active="win",state={game:"",team:"ソフトバンク",metricKind:"hitter",league:"パ",qualified:false,draftYear:"",oddsLeague:"パ",alertKind:"batter",alertDirection:"all"};
  function e(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
  function n(v){var x=Number(v);return Number.isFinite(x)?x:0;}
  function f(v,d){var x=Number(v);return Number.isFinite(x)?x.toFixed(d==null?1:d):"-";}
  function pct(v){return f(100*n(v),1)+"%";}
  function badge(label,kind){return '<span class="badge '+e(kind||"")+'">'+e(label)+'</span>';}
  function hero(kicker,title,desc,note){return '<div class="hero"><div><div class="eyebrow">'+e(kicker)+'</div><h2>'+e(title)+'</h2><div class="sub">'+e(desc)+'</div></div>'+(note?'<div class="note">'+e(note)+'</div>':'')+'</div>';}
  function table(headers,rows){return '<div class="scroll"><table class="tbl"><thead><tr>'+headers.map(function(x){return '<th>'+e(x)+'</th>';}).join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>';}
  function gameLabel(g){return g.date+'　'+g.away+' '+g.away_score+'－'+g.home_score+' '+g.home;}
  function wpChart(game){
    var rows=game.timeline||[];if(!rows.length)return '<div class="empty">勝率推移を算出できる打席がありません</div>';
    var W=980,H=330,p={l:44,r:18,t:20,b:42},X=function(i){return p.l+i/Math.max(1,rows.length-1)*(W-p.l-p.r);},Y=function(v){return p.t+(1-v)*(H-p.t-p.b);};
    var points=rows.map(function(r,i){return X(i).toFixed(1)+','+Y(n(r.home_wp)).toFixed(1);}).join(' '),area=p.l+','+Y(.5)+' '+points+' '+X(rows.length-1)+','+Y(.5);
    var grid=[0,.25,.5,.75,1].map(function(q){var y=Y(q);return '<line class="'+(q===.5?'mid':'gridline')+'" x1="'+p.l+'" y1="'+y+'" x2="'+(W-p.r)+'" y2="'+y+'"/><text x="4" y="'+(y+4)+'">'+Math.round(q*100)+'%</text>';}).join('');
    var labels=[],last=0;rows.forEach(function(r,i){var key=r.inning+r.half;if(key!==last){labels.push('<text x="'+X(i)+'" y="'+(H-12)+'">'+e(key)+'</text>');last=key;}});
    var dots=(game.top_swings||[]).map(function(s){var i=rows.indexOf(s);if(i<0)i=rows.findIndex(function(r){return r.seq===s.seq;});return '<circle class="point" cx="'+X(i)+'" cy="'+Y(n(s.home_wp))+'" r="5"><title>'+e(s.inning+s.half+' '+s.batter+' '+s.result+' / '+pct(Math.abs(s.delta))+'変動')+'</title></circle>';}).join('');
    return '<svg class="wp-chart" viewBox="0 0 '+W+' '+H+'" role="img" aria-label="ホームチームの推定勝率推移"><defs><linearGradient id="wpArea" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#ef5609"/><stop offset="1" stop-color="#fff"/></linearGradient></defs>'+grid+'<polygon class="area-home" points="'+area+'"/><polyline class="line" points="'+points+'"/>'+dots+labels.join('')+'<text x="'+(W-126)+'" y="14">ホーム勝率</text></svg>';
  }
  function renderWin(){
    var part=data.win_probability||{},games=part.games||[];if(!state.game&&games[0])state.game=games[0].game_id;var game=games.find(function(g){return g.game_id===state.game;})||games[0];
    var select='<label>試合<select id="dl-game">'+games.map(function(g){return '<option value="'+e(g.game_id)+'"'+(game&&g.game_id===game.game_id?' selected':'')+'>'+e(gameLabel(g))+'</option>';}).join('')+'</select></label>';
    if(!game)return hero('WIN PROBABILITY','試合勝率','打席ごとの推定勝率を表示','対象試合なし')+'<div class="empty">試合データがありません</div>';
    var swings=(game.top_swings||[]).map(function(s,i){var cls=s.delta>=0?'pos':'neg';return '<div class="swing"><span class="rank">#'+(i+1)+'</span><b>'+e(s.inning+s.half)+'</b><span><b>'+e(s.batter)+'</b>　'+e(s.result)+'<br><small>'+e(s.pitcher)+'から / '+s.away_score+'－'+s.home_score+'</small></span><span class="delta '+cls+'">'+(s.delta>=0?'+':'')+pct(s.delta)+'</span></div>';}).join('');
    return hero('WIN PROBABILITY','試合別 勝利確率','試合の流れと勝敗を大きく動かした打席を確認',part.model)+
      '<div class="grid"><section class="card wide"><div class="controls">'+select+'</div><div class="kpis"><div class="kpi"><b>'+e(game.away_score+'－'+game.home_score)+'</b><span>'+e(game.away+' vs '+game.home)+'</span></div><div class="kpi"><b>'+e(game.winner||'引分')+'</b><span>勝利球団</span></div><div class="kpi"><b>'+n(game.timeline.length)+'</b><span>評価打席</span></div><div class="kpi"><b>'+e(game.stadium)+'</b><span>球場 · 得点経過'+(game.score_reconstruction_complete?'復元済':'一部推定')+'</span></div></div>'+wpChart(game)+'</section><section class="card wide"><h3>勝率を動かしたプレー TOP5</h3>'+swings+'</section><section class="card wide note">'+e(part.caution)+'</section></div>';
  }
  function renderBullpen(){
    var part=data.bullpen||{},teams=part.teams||[];if(!teams.some(function(x){return x.team===state.team;})&&teams[0])state.team=teams[0].team;var team=teams.find(function(x){return x.team===state.team;})||{players:[]};
    var select='<label>球団<select id="dl-team">'+teams.map(function(x){return '<option'+(x.team===state.team?' selected':'')+'>'+e(x.team)+'</option>';}).join('')+'</select></label>';
    var rows=team.players.map(function(p){var kind=p.workload==='高負荷'?'high':p.workload==='注意'?'warn':'ok';return '<tr><td><b>'+e(p.name)+'</b></td><td>'+e(p.role)+'</td><td>'+badge(p.workload,kind)+'</td><td class="num">'+p.pitches_yesterday+'</td><td class="num">'+p.pitches_last_3_days+'</td><td class="num">'+p.apps_last_3_days+'</td><td class="num">'+p.apps_last_5_days+'</td><td class="num">'+p.consecutive_days+'</td><td class="num">'+p.days_since+'</td><td class="num">'+p.holds+'</td><td class="num">'+p.saves+'</td></tr>';});
    return hero('BULLPEN WORKLOAD','ブルペン負荷','直近の球数・連投から「今日までの負荷」を整理',part.data_date+'時点')+'<div class="grid"><section class="card wide"><div class="controls">'+select+'</div>'+table(['投手','役割','負荷','前日球数','3日球数','3日登板','5日登板','連投日','最終登板から','H','S'],rows)+'</section><section class="card wide note"><b>判定ルール</b><br>'+e((part.rules||[]).join(' / '))+'<br>'+e(part.note)+'</section></div>';
  }
  function renderAdjusted(){
    var part=data.adjusted_metrics||{},isHit=state.metricKind==='hitter',pool=isHit?(part.hitters||[]):(part.pitchers||[]);pool=pool.filter(function(x){return (state.league==='全'||x.league===state.league)&&(!state.qualified||x.qualified);}).slice(0,100);
    var controls='<label>対象<select id="dl-mkind"><option value="hitter"'+(isHit?' selected':'')+'>野手</option><option value="pitcher"'+(!isHit?' selected':'')+'>投手</option></select></label><label>リーグ<select id="dl-league"><option'+(state.league==='全'?' selected':'')+'>全</option><option'+(state.league==='セ'?' selected':'')+'>セ</option><option'+(state.league==='パ'?' selected':'')+'>パ</option></select></label><label>規定<select id="dl-qualified"><option value="all"'+(!state.qualified?' selected':'')+'>全選手</option><option value="yes"'+(state.qualified?' selected':'')+'>規定到達のみ</option></select></label>';
    var headers=isHit?['#','選手','球団','PA','OPS','wOBA','PF','OPS+','推定wRC+']:['#','投手','球団','回','ERA','FIP','PF','ERA-','FIP-'];
    var rows=pool.map(function(p,i){return isHit?'<tr><td class="rank">'+(i+1)+'</td><td><b>'+e(p.name)+'</b></td><td>'+e(p.team)+'</td><td class="num">'+p.pa+'</td><td class="num">'+f(p.ops,3)+'</td><td class="num">'+f(p.woba,3)+'</td><td class="num">'+f(p.park_factor,3)+'</td><td class="num strong">'+f(p.ops_plus,1)+'</td><td class="num strong">'+f(p.wrc_plus_est,1)+'</td></tr>':'<tr><td class="rank">'+(i+1)+'</td><td><b>'+e(p.name)+'</b></td><td>'+e(p.team)+'</td><td class="num">'+f(p.innings,1)+'</td><td class="num">'+f(p.era,2)+'</td><td class="num">'+f(p.fip,2)+'</td><td class="num">'+f(p.park_factor,3)+'</td><td class="num strong">'+f(p.era_minus,1)+'</td><td class="num strong">'+f(p.fip_minus,1)+'</td></tr>';});
    var parks=(part.parks||[]).map(function(p){return '<tr><td><b>'+e(p.team)+'</b></td><td>'+e(p.stadium)+'</td><td class="num">'+p.home_games+'</td><td class="num">'+f(p.home_runs_per_game,2)+'</td><td class="num">'+f(p.away_runs_per_game,2)+'</td><td class="num strong">'+f(p.factor,3)+'</td></tr>';});
    return hero('PARK ADJUSTED','球場補正指標','100がリーグ平均。OPS+/wRC+は高いほど、ERA-/FIP-は低いほど優秀','単年・縮小推定')+'<div class="grid"><section class="card wide"><div class="controls">'+controls+'</div>'+table(headers,rows)+'</section><section class="card wide"><h3>単年パークファクター</h3>'+table(['球団','主な本拠地','本拠地試合','本拠地 総得点/試合','遠征 総得点/試合','PF'],parks)+'</section><section class="card wide note">'+e(part.method)+'<br>'+e(part.caution)+'</section></div>';
  }
  function renderDraft(){
    var part=data.draft_review||{},cohorts=part.cohorts||[];if(!state.draftYear&&cohorts[0])state.draftYear=String(cohorts[0].year);var cur=cohorts.find(function(x){return String(x.year)===state.draftYear;})||cohorts[0];
    var select='<label>ドラフト年度<select id="dl-draftyear">'+cohorts.map(function(c){return '<option value="'+c.year+'"'+(cur&&c.year===cur.year?' selected':'')+'>'+c.year+'年度</option>';}).join('')+'</select></label>';
    var leaders=function(rows,key,unit){return (rows||[]).map(function(p,i){return (i+1)+'. '+e(p.name)+'（'+e(p.team)+'） '+f(p[key],key==='career_innings'?1:0)+unit;}).join('<br>')||'対象なし';};
    var roundRows=(part.rounds||[]).map(function(r){return '<tr><td>'+e(r.route+r.rank+'位')+'</td><td class="num">'+r.players+'</td><td class="num">'+f(r.debut_rate,1)+'%</td><td class="num">'+f(r.career_pa_per_player,1)+'</td><td class="num">'+f(r.career_innings_per_player,1)+'</td></tr>';});
    return hero('DRAFT RETROSPECTIVE','ドラフト答え合わせ','年度別・指名順位別に一軍到達と通算出場量を確認','成績の優劣ではなくキャリア量の記述')+'<div class="grid"><section class="card wide"><div class="controls">'+select+'</div>'+(cur?'<div class="kpis"><div class="kpi"><b>'+cur.players+'</b><span>収録選手</span></div><div class="kpi"><b>'+f(cur.debut_rate,1)+'%</b><span>一軍出場あり</span></div><div class="kpi"><b>'+cur.career_pa_total.toLocaleString()+'</b><span>通算打席 合計</span></div><div class="kpi"><b>'+f(cur.career_innings_total,1)+'</b><span>通算投球回 合計</span></div></div>':'')+'</section>'+(cur?'<section class="card"><h3>通算打席 上位</h3><div class="leaders">'+leaders(cur.top_batters,'career_pa','打席')+'</div></section><section class="card"><h3>通算投球回 上位</h3><div class="leaders">'+leaders(cur.top_pitchers,'career_innings','回')+'</div></section>':'')+'<section class="card wide"><h3>指名順位別</h3>'+table(['区分','収録数','一軍出場率','平均通算打席','平均通算投球回'],roundRows)+'</section><section class="card wide note">'+e(part.note)+'</section></div>';
  }
  function renderOdds(){
    var part=data.playoff_odds||{},rows=((part.leagues||{})[state.oddsLeague]||[]);var controls='<label>リーグ<select id="dl-oddsleague"><option'+(state.oddsLeague==='セ'?' selected':'')+'>セ</option><option'+(state.oddsLeague==='パ'?' selected':'')+'>パ</option></select></label>';
    var content=rows.map(function(r){return '<div class="odds-row"><b>'+e(r.team)+'</b><div><div class="meter"><i style="width:'+Math.max(1,r.pennant_pct)+'%"></i></div><small>予想 '+f(r.expected_wins,1)+'勝 / 残'+r.games_left+'</small></div><span class="num strong">'+f(r.pennant_pct,1)+'%</span><span class="num">'+f(r.cs_pct,1)+'%</span></div>';}).join('');
    return hero('MONTE CARLO','優勝・CS確率','現時点の成績が続くと仮定した10,000回シミュレーション','予定表未使用の感度分析')+'<div class="grid"><section class="card wide"><div class="controls">'+controls+'</div><div class="odds-row"><b>球団</b><span></span><b class="num">優勝</b><b class="num">CS</b></div>'+content+'</section><section class="card wide note">'+e(part.method)+'<br>'+e(part.caution)+'</section></div>';
  }
  function renderAlerts(){
    var part=data.change_alerts||{},isBat=state.alertKind==='batter',pool=(isBat?part.batters:part.pitchers)||[];if(state.alertDirection!=='all')pool=pool.filter(function(x){return x.direction===state.alertDirection;});
    var dirs=isBat?['all','上昇','低下']:['all','改善','悪化'];var controls='<label>対象<select id="dl-alertkind"><option value="batter"'+(isBat?' selected':'')+'>野手</option><option value="pitcher"'+(!isBat?' selected':'')+'>投手</option></select></label><label>変化<select id="dl-alertdir">'+dirs.map(function(x){return '<option value="'+x+'"'+(x===state.alertDirection?' selected':'')+'>'+(x==='all'?'すべて':x)+'</option>';}).join('')+'</select></label>';
    var headers=isBat?['選手','球団','変化','直近','以前','差','標本','信頼度']:['投手','球団','役割','変化','直近ERA','以前ERA','差','標本','信頼度'];
    var rows=pool.map(function(p){var good=p.direction==='上昇'||p.direction==='改善',b=badge(p.direction,good?'up':'down');return isBat?'<tr><td><b>'+e(p.name)+'</b></td><td>'+e(p.team)+'</td><td>'+b+'</td><td class="num strong">'+f(p.recent_ops,3)+'</td><td class="num">'+f(p.baseline_ops,3)+'</td><td class="num">'+(p.delta>0?'+':'')+f(p.delta,3)+'</td><td>'+p.recent_games+'試合 '+p.recent_pa+'打席</td><td>'+badge(p.confidence,p.confidence==='中'?'warn':'')+'</td></tr>':'<tr><td><b>'+e(p.name)+'</b></td><td>'+e(p.team)+'</td><td>'+e(p.role)+'</td><td>'+b+'</td><td class="num strong">'+f(p.recent_era,2)+'</td><td class="num">'+f(p.baseline_era,2)+'</td><td class="num">'+(p.delta>0?'+':'')+f(p.delta,2)+'</td><td>'+p.recent_games+'登板 '+f(p.recent_innings,1)+'回</td><td>'+badge(p.confidence,p.confidence==='中'?'warn':'')+'</td></tr>';});
    return hero('CHANGE DETECTOR','成績変化アラート','直近とそれ以前の差が大きい選手を標本条件つきで抽出','原因ではなく「見るべき変化」')+'<div class="grid"><section class="card wide"><div class="controls">'+controls+'</div>'+table(headers,rows)+'</section><section class="card wide note"><b>抽出条件</b> '+e((part.rules||[]).join(' / '))+'<br>'+e(part.caution)+'</section></div>';
  }
  function render(){var app=document.getElementById('app');if(!data)return;var fn={win:renderWin,bullpen:renderBullpen,adjusted:renderAdjusted,draft:renderDraft,odds:renderOdds,alerts:renderAlerts}[active];app.innerHTML=fn();bindControls();}
  function bindControls(){
    function on(id,key,transform){var x=document.getElementById(id);if(x)x.onchange=function(){state[key]=transform?transform(x.value):x.value;render();};}
    on('dl-game','game');on('dl-team','team');on('dl-mkind','metricKind');on('dl-league','league');on('dl-qualified','qualified',function(v){return v==='yes';});on('dl-draftyear','draftYear');on('dl-oddsleague','oddsLeague');on('dl-alertkind','alertKind',function(v){state.alertDirection='all';return v;});on('dl-alertdir','alertDirection');
  }
  document.querySelectorAll('[data-tab]').forEach(function(button){button.onclick=function(){document.querySelectorAll('[data-tab]').forEach(function(x){x.classList.toggle('on',x===button);});active=button.dataset.tab;render();};});
  fetch('data/2026/decision_lab.json?t='+Date.now()).then(function(res){if(!res.ok)throw new Error('HTTP '+res.status);return res.json();}).then(function(json){data=json;document.getElementById('status').textContent=(data.data_date||data.season)+' 時点';render();}).catch(function(err){document.getElementById('status').textContent='data error';document.getElementById('app').innerHTML='<div class="note"><b>分析データを読み込めません。</b><br>'+e(err.message)+'<br>Daily ActionsでDECISION LABデータを生成してください。</div>';});
})();
