(function(){
  "use strict";
  var STORE="npb-chat-v1", state={open:false,busy:false,data:null,history:[],memory:{likes:[],preferences:[]}};
  var TEAMS={"ソフトバンク":["ソフトバンク","ホークス","sbhawks"],"日本ハム":["日本ハム","ファイターズ"],"オリックス":["オリックス","バファローズ"],"楽天":["楽天","イーグルス"],"西武":["西武","ライオンズ"],"ロッテ":["ロッテ","マリーンズ"],"阪神":["阪神","タイガース"],"DeNA":["dena","横浜","ベイスターズ"],"巨人":["巨人","ジャイアンツ"],"中日":["中日","ドラゴンズ"],"広島":["広島","カープ"],"ヤクルト":["ヤクルト","スワローズ"]};
  var METRICS={ops:{words:["ops"],label:"OPS",kind:"batting",digits:3},avg:{words:["打率","avg"],label:"打率",kind:"batting",digits:3},hr:{words:["本塁打","ホームラン","hr"],label:"本塁打",kind:"batting",digits:0},rbi:{words:["打点","rbi"],label:"打点",kind:"batting",digits:0},hits:{words:["安打"],label:"安打",kind:"batting",digits:0},sb:{words:["盗塁"],label:"盗塁",kind:"batting",digits:0},wrc_plus_est:{words:["wrc+","wrc＋"],label:"推定wRC+",kind:"batting",digits:0},era:{words:["防御率","era"],label:"防御率",kind:"pitching",digits:2,lower:true},whip:{words:["whip"],label:"WHIP",kind:"pitching",digits:2},so:{words:["奪三振"],label:"奪三振",kind:"pitching",digits:0},wins:{words:["勝利数","勝利"],label:"勝利",kind:"pitching",digits:0},saves:{words:["セーブ"],label:"セーブ",kind:"pitching",digits:0},k9:{words:["k/9","奪三振率"],label:"K/9",kind:"pitching",digits:2}};
  var GLOSSARY={"RE24":"24通りのアウト・走者状態を基準に、プレー前後の得点期待値の変化を合計する指標です。プラスほど得点創出への貢献が大きいことを示します。","WPA":"プレー前後の勝利確率の変化を合計する指標です。当サイトでは公式値ではなく、収集試合から作った縮小推定モデルを使用します。","OPS":"出塁率と長打率を足した打撃指標です。出塁と長打を一つの数字で確認できます。","WAR":"代替可能な選手と比べ、何勝分の価値を生んだかを表す総合指標です。当サイトのWARは取得可能データだけを使う簡易推定です。","wRC+":"打撃による得点創出をリーグ平均100で表す指標です。当サイトの推定wRC+は球場効果未補正です。","FIP":"奪三振・与四死球・被本塁打を中心に、守備の影響を減らして投手を評価する指標です。"};
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c];});}
  function compact(v){return String(v||"").toLowerCase().replace(/[\s・　]/g,"").replace(/[髙﨑濵濱邉邊齋澤]/g,function(c){return{"髙":"高","﨑":"崎","濵":"浜","濱":"浜","邉":"辺","邊":"辺","齋":"斎","澤":"沢"}[c];});}
  function fmt(v,d){var x=Number(v);if(!Number.isFinite(x))return "-";var s=x.toFixed(d);return d>0&&x>=0&&x<1?s.replace(/^0/,""):s;}
  function loadStore(){try{var v=JSON.parse(localStorage.getItem(STORE)||"{}");state.history=Array.isArray(v.history)?v.history.slice(-30):[];state.memory=v.memory||state.memory;}catch(e){}}
  function saveStore(){try{localStorage.setItem(STORE,JSON.stringify({history:state.history.slice(-30),memory:state.memory}));}catch(e){}}
  function inject(){loadStore();document.body.insertAdjacentHTML("beforeend",'<button class="npc-launch" id="npcLaunch" aria-label="NPBデータチャットを開く"><span class="npc-launch-dot"></span>AIチャット</button><section class="npc-panel" id="npcPanel" aria-label="NPBデータコンシェルジュ"><header class="npc-head"><div class="npc-avatar">⚾</div><div class="npc-head-main"><div class="npc-title">NPBデータコンシェルジュ</div><div class="npc-status">サイト内データを根拠に回答</div></div><button class="npc-iconbtn" id="npcReset" title="会話をリセット">↻</button><button class="npc-iconbtn" id="npcClose" aria-label="閉じる">×</button></header><div class="npc-disclosure">質問・検索した公開成績・端末内の好み／高評価例をPuter AIへ送ります。AIが使えない場合はデータ回答へ自動で切り替えます。</div><div class="npc-log" id="npcLog"></div><div class="npc-footer"><div class="npc-chips" id="npcChips"></div><div class="npc-compose"><textarea class="npc-input" id="npcInput" rows="2" placeholder="例：柳田悠岐の成績を教えて"></textarea><button class="npc-send" id="npcSend" aria-label="送信">➤</button><div class="npc-memory"><span id="npcMemoryLabel"></span><button id="npcMemoryClear">学習メモリを消す</button></div></div></div></section>');bind();renderHistory();}
  function bind(){document.getElementById("npcLaunch").onclick=open;document.getElementById("npcClose").onclick=close;document.getElementById("npcReset").onclick=function(){state.history=[];saveStore();renderHistory();};document.getElementById("npcMemoryClear").onclick=function(){state.memory={likes:[],preferences:[]};saveStore();renderMemory();};document.getElementById("npcSend").onclick=send;document.getElementById("npcInput").addEventListener("keydown",function(ev){if(ev.key==="Enter"&&!ev.shiftKey){ev.preventDefault();send();}});document.getElementById("npcLog").addEventListener("click",function(ev){var p=ev.target.closest("[data-npc-player]");if(p&&typeof gotoPlayer==="function"){close();gotoPlayer(p.dataset.npcPlayer);}var r=ev.target.closest("[data-npc-rate]");if(r)rate(Number(r.dataset.npcIndex),r.dataset.npcRate);});}
  function open(){state.open=true;document.getElementById("npcPanel").classList.add("on");document.getElementById("npcLaunch").style.display="none";renderHistory();setTimeout(function(){document.getElementById("npcInput").focus();},80);}
  function close(){state.open=false;document.getElementById("npcPanel").classList.remove("on");document.getElementById("npcLaunch").style.display="flex";}
  function chips(){return ["柳田悠岐の成績","OPS上位5人","パ・リーグの順位","8月のMVP候補","RE24って何？","柳田と近藤を比較"]}
  function renderHistory(){var log=document.getElementById("npcLog"),cs=document.getElementById("npcChips");if(!log)return;if(!state.history.length){log.innerHTML='<div class="npc-msg npc-bot">こんにちは！ NPBの選手成績、ランキング、順位表、表彰、指標について聞いてください。<span class="npc-meta">収集済み公開データだけを使います</span></div>';}else{log.innerHTML=state.history.map(function(m,i){var actions=m.role==="assistant"?'<div class="npc-actions">'+(m.players||[]).map(function(p){return '<button class="npc-player-link" data-npc-player="'+esc(p.key)+'">'+esc(p.name)+'の詳細</button>';}).join("")+'<span class="npc-rate"><button class="npc-action" data-npc-index="'+i+'" data-npc-rate="up">👍</button><button class="npc-action" data-npc-index="'+i+'" data-npc-rate="down">👎</button></span></div>':"";return '<div class="npc-msg '+(m.role==="user"?'npc-user':'npc-bot')+'">'+esc(m.text)+(m.meta?'<span class="npc-meta">'+esc(m.meta)+'</span>':'')+actions+'</div>';}).join("");}cs.innerHTML=chips().map(function(x){return '<button class="npc-chip">'+esc(x)+'</button>';}).join("");cs.querySelectorAll("button").forEach(function(b){b.onclick=function(){document.getElementById("npcInput").value=b.textContent;send();};});renderMemory();log.scrollTop=log.scrollHeight;}
  function renderMemory(){var n=(state.memory.likes||[]).length+(state.memory.preferences||[]).length,el=document.getElementById("npcMemoryLabel");if(el)el.textContent=n?"学習メモリ "+n+"件":"会話と評価はこの端末だけに保存";}
  async function loadData(){if(state.data)return state.data;var year=(new Date()).getFullYear(),base="data/"+year+"/";var paths=[base+"players/stats.json",base+"teams/stats.json",base+"standings.json","data/masters/player_profiles.json",base+"awards/monthly/"+year+"-"+String(new Date().getMonth()+1).padStart(2,"0")+".json"];var values=await Promise.all(paths.map(async function(p){try{var r=await fetch(p+"?t="+Date.now());return r.ok?await r.json():null;}catch(e){return null;}}));state.data={year:year,players:(values[0]||{}).players||[],teams:(values[1]||{}).teams||[],standings:values[2]||{},profiles:(values[3]||{}).players||[],awards:values[4]||null,updated:(values[2]||{}).updated_at||(values[0]||{}).generated_at||""};return state.data;}
  function findTeam(q){var cq=compact(q),found=null;Object.keys(TEAMS).some(function(team){return TEAMS[team].some(function(a){if(cq.indexOf(compact(a))>=0){found=team;return true;}return false;});});return found;}
  function findPlayers(q,data){var cq=compact(q),hits=data.players.filter(function(p){var name=compact(p.name);return name&&cq.indexOf(name)>=0;});if(hits.length)return hits.sort(function(a,b){return cq.indexOf(compact(a.name))-cq.indexOf(compact(b.name));});var tokens=cq.split(/(?:と|vs|対|、|,)/i).map(function(x){return x.replace(/(を比較|の成績|について|教えて|見せて|選手)$/g,"");}).filter(function(x){return x.length>=2;}),out=[];tokens.forEach(function(t){var best=data.players.filter(function(p){var name=compact(p.name);return name.indexOf(t)>=0||t.indexOf(name)>=0;}).sort(function(a,b){return volume(b)-volume(a);})[0];if(best&&!out.some(function(x){return x.key===best.key;}))out.push(best);});return out.slice(0,3);}
  function volume(p){return Number((p.batting||{}).pa||0)+Number((p.pitching||{}).outs||0);}
  function playerLine(p){var b=p.batting||{},x=p.pitching||{};if(Number(x.outs)>Number(b.pa)){return p.name+'（'+p.team+'） '+Number(x.games||0)+'登板 '+String(x.innings||'0')+'回 防御率'+fmt(x.era,2)+' WHIP'+fmt(x.whip,2)+' '+Number(x.so||0)+'奪三振';}return p.name+'（'+p.team+'） '+Number(b.games||0)+'試合 '+Number(b.pa||0)+'打席 打率'+fmt(b.avg,3)+' OPS'+fmt(b.ops,3)+' '+Number(b.hr||0)+'本塁打 '+Number(b.rbi||0)+'打点 '+Number(b.sb||0)+'盗塁';}
  function playerAnswer(players,data,q){if(players.length>=2&&/(比較|比べ|と|vs|対)/i.test(q)){return {text:playerLine(players[0])+'\n'+playerLine(players[1])+'\n出場量が異なるため、率指標と累積成績を分けて比較してください。',facts:players.slice(0,2).map(playerLine).join(" / "),players:players.slice(0,2).map(function(p){return {key:p.key,name:p.name};})};}var p=players[0],profile=data.profiles.find(function(x){return compact(x.name)===compact(p.name)&&(!x.team||x.team===p.team);});var text=playerLine(p);if(profile&&/(プロフィール|出身|生年月日|経歴|学校)/.test(q)){text+='\n生年月日 '+(profile.birthdate||'未取得')+'、出身地 '+(profile.birthplace||'未取得')+'、経歴 '+(profile.career||'未取得')+'。';}return {text:text,facts:text,players:[{key:p.key,name:p.name}]};}
  function metricOf(q){var cq=compact(q),result=null;Object.keys(METRICS).some(function(k){var m=METRICS[k];if(m.words.some(function(w){return cq.indexOf(compact(w))>=0;})){result={key:k,def:m};return true;}return false;});return result||{key:"ops",def:METRICS.ops};}
  function rankingAnswer(q,data){var m=metricOf(q),team=findTeam(q),kind=m.def.kind,rows=data.players.filter(function(p){var s=p[kind]||{};return (!team||p.team===team)&&s[m.key]!=null&&Number(kind==="batting"?s.pa:s.outs)>0;}),maxGames=Math.max.apply(null,([].concat(data.standings.central||[],data.standings.pacific||[])).map(function(x){return Number(x.games)||0;}).concat([0])),rateMetric=["ops","avg","era"].indexOf(m.key)>=0,qualified=(rateMetric||/規定/.test(q))&&!/(規定外|全選手)/.test(q);if(qualified)rows=rows.filter(function(p){var s=p[kind]||{};return Number(s[kind==="batting"?"pa":"outs"])>=(kind==="batting"?maxGames*3.1:maxGames*3);});rows.sort(function(a,b){var av=Number((a[kind]||{})[m.key]),bv=Number((b[kind]||{})[m.key]);return m.def.lower?av-bv:bv-av;});var count=Math.min(10,Number((q.match(/(\d+)人/)||[])[1]||5)),top=rows.slice(0,count),text=(team?team+"の":"")+m.def.label+"上位"+count+"人"+(qualified?"（規定到達者）":"")+"\n"+top.map(function(p,i){return (i+1)+". "+p.name+"（"+p.team+"） "+fmt((p[kind]||{})[m.key],m.def.digits)+"［"+(kind==="batting"?Number((p[kind]||{}).pa||0)+"打席":String((p[kind]||{}).innings||"0")+"回")+"］";}).join("\n");return {text:text,facts:text,players:top.map(function(p){return {key:p.key,name:p.name};})};}
  function standingsAnswer(q,data){var team=findTeam(q),rows=[].concat(data.standings.central||[],data.standings.pacific||[]);if(team){var r=rows.find(function(x){return x.team===team;});if(!r)return null;var text=team+'は'+r.rank+'位、'+r.wins+'勝'+r.losses+'敗'+r.ties+'分、勝率'+fmt(r.pct,3)+'、首位との差'+r.gb+'です。';return {text:text,facts:text};}var text=["セ・リーグ",data.standings.central||[],"パ・リーグ",data.standings.pacific||[]];text='セ・リーグ\n'+(data.standings.central||[]).map(function(r){return r.rank+'. '+r.team+' '+r.wins+'勝'+r.losses+'敗 勝率'+fmt(r.pct,3);}).join("\n")+'\n\nパ・リーグ\n'+(data.standings.pacific||[]).map(function(r){return r.rank+'. '+r.team+' '+r.wins+'勝'+r.losses+'敗 勝率'+fmt(r.pct,3);}).join("\n");return {text:text,facts:text};}
  function awardsAnswer(q,data){if(!data.awards)return null;var league=/セ/.test(q)?"セ":/パ/.test(q)?"パ":null,parts=league?[league]:["セ","パ"],lines=[];parts.forEach(function(lg){var x=(data.awards.leagues||{})[lg];if(x&&x.batter_mvp)lines.push(lg+'・リーグ野手MVP候補 '+x.batter_mvp.name+'（'+x.batter_mvp.team+'） '+x.batter_mvp.score+'点 '+x.batter_mvp.stat_line);if(x&&x.pitcher_mvp)lines.push(lg+'・リーグ投手MVP候補 '+x.pitcher_mvp.name+'（'+x.pitcher_mvp.team+'） '+x.pitcher_mvp.score+'点');});var text=lines.join("\n");return {text:text,facts:text};}
  function glossaryAnswer(q){if(!/(って何|とは|意味|解説|説明して)/.test(q)||/(上位|ランキング|トップ|top)/i.test(q))return null;var key=Object.keys(GLOSSARY).find(function(k){return compact(q).indexOf(compact(k))>=0;});return key?{text:key+'：'+GLOSSARY[key],facts:key+'='+GLOSSARY[key]}:null;}
  function remember(q,data){var team=findTeam(q),players=findPlayers(q,data);if(!/(覚えて|ファン|推し)/.test(q))return null;var value=team||((players[0]||{}).name);if(!value)return null;if(state.memory.preferences.indexOf(value)<0)state.memory.preferences.push(value);saveStore();return {text:value+'をあなたの好みとして、この端末に覚えました。今後の質問で優先的に参照します。',facts:'ユーザーの好み='+value};}
  function analyze(q,data){var remembered=remember(q,data);if(remembered)return remembered;var g=glossaryAnswer(q);if(g)return g;var ps=findPlayers(q,data);if(ps.length)return playerAnswer(ps,data,q);if(/順位|勝敗|首位|ゲーム差/.test(q))return standingsAnswer(q,data);if(/mvp|表彰|ベストメンバー/i.test(q))return awardsAnswer(q,data)||{text:"対象期間の表彰データがまだありません。",facts:"表彰データなし"};if(/上位|ランキング|トップ|top/i.test(q)||Object.keys(METRICS).some(function(k){return METRICS[k].words.some(function(w){return compact(q).indexOf(compact(w))>=0;});}))return rankingAnswer(q,data);return {text:"選手名、球団、指標、期間を含めて質問してください。例：『柳田悠岐の成績』『OPS上位5人』『パ・リーグの順位』『RE24って何？』",facts:"質問を特定できず"};}
  function aiText(response){if(typeof response==="string")return response.trim();var c=response&&response.message&&response.message.content;if(typeof c==="string")return c.trim();if(Array.isArray(c))return c.map(function(x){return typeof x==="string"?x:String((x||{}).text||"");}).join("").trim();return String((response&&(response.text||response.response))||"").trim();}
  async function enhance(q,result,data){if(!window.puter||!puter.ai||typeof puter.ai.chat!=="function"||result.facts==="質問を特定できず")return result.text;var prefs=(state.memory.preferences||[]).join("、")||"なし",examples=(state.memory.likes||[]).slice(-3).map(function(x){return '質問:'+x.q+' 回答:'+x.a;}).join("\n")||"なし";var prompt="あなたはNPBデータサイトのアナリストです。次の根拠だけを使い、日本語で簡潔に回答してください。根拠にない数字・故障・将来予測を作らないでください。回答の最初に結論を書き、必要なら標本数に注意してください。\n質問:"+q+"\n根拠:"+result.facts+"\nユーザーの好み:"+prefs+"\n高評価だった回答例:"+examples;try{var response=await Promise.race([puter.ai.chat(prompt),new Promise(function(_,reject){setTimeout(function(){reject(new Error("AI timeout"));},8000);})]);return aiText(response)||result.text;}catch(e){return result.text;}}
  async function send(){if(state.busy)return;var input=document.getElementById("npcInput"),q=input.value.trim();if(!q)return;input.value="";state.history.push({role:"user",text:q});state.busy=true;renderHistory();var log=document.getElementById("npcLog");log.insertAdjacentHTML("beforeend",'<div class="npc-msg npc-bot npc-thinking" id="npcThinking">サイト内データを検索しています…</div>');log.scrollTop=log.scrollHeight;try{var data=await loadData(),result=analyze(q,data),index=state.history.length,meta=(data.updated?String(data.updated).slice(0,10)+"時点 ／ ":"")+"収集済み公開データ";state.history.push({role:"assistant",text:result.text,localText:result.text,facts:result.facts,players:result.players||[],meta:meta+" ／ AI文章化中"});saveStore();renderHistory();var answer=await enhance(q,result,data);if(state.history[index]){state.history[index].text=answer;state.history[index].meta=meta+(answer===result.text?" ／ データ回答":" ／ AI回答");}}catch(e){state.history.push({role:"assistant",text:"データを読み込めませんでした。時間をおいてもう一度お試しください。",meta:String(e.message||e)});}finally{state.busy=false;saveStore();renderHistory();}}
  function rate(index,value){var m=state.history[index];if(!m||m.role!=="assistant")return;m.rating=value;if(value==="up"&&m.facts){state.memory.likes.push({q:(state.history[index-1]||{}).text||"",a:m.localText||m.text,facts:m.facts});state.memory.likes=state.memory.likes.slice(-10);}saveStore();renderHistory();}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",inject);else inject();
})();
