(function() {
  'use strict';
  const M=window.Workbench,$=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fmt=(v,d=3)=>v==null?'—':Number(v).toFixed(d),pct=v=>v==null?'—':(v*100).toFixed(1)+'%';
  const table=(heads,rows)=>'<div class="scroll"><table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.join('')+'</tbody></table></div>';
  const fields=['role','player','hand','risp','a0','a1','b0','b1','type','count','zone'];
  const season=new URLSearchParams(location.search).get('season')||'2026';
  const base='data/'+(/^\d{4}$/.test(season)?season:'2026')+'/dataset/workbench/';
  const storageKey='npb-workbench-presets-v1';
  let manifest,playerData,result,applied,loadToken=0,presets=[],alertLimit=30,sequenceLimit=30,evidenceLimit=30,evidenceRows=[],evidenceLabel='';
  const snapshot=()=>Object.fromEntries(fields.map(f=>[f,$(f).value]));
  function message(text){$('message').textContent=text;}
  function options(id,values,selected='',all=true){$(id).replaceChildren(...(all?[new Option('すべて','')]:[]),...values.map(x=>new Option(typeof x==='string'?x:x.label,typeof x==='string'?x:x.value)));$(id).value=selected;if($(id).selectedIndex<0)$(id).selectedIndex=0;}
  async function json(path){const r=await fetch(path);if(!r.ok)throw new Error('データの読み込みに失敗しました（HTTP '+r.status+'）。');return r.json();}
  function dirty(){ $('results').hidden=true;result=null;message('条件を変更しました。「この条件で比較」で更新してください。'); }
  function populatePlayers(preferred){
    const query=$('search').value.trim().toLocaleLowerCase();
    const list=manifest.players.filter(p=>p.role===$('role').value&&(!query||(p.name+' '+p.team).toLocaleLowerCase().includes(query))).sort((a,b)=>b.atbats-a.atbats||a.name.localeCompare(b.name,'ja'));
    options('player',list.map(p=>({value:p.id,label:p.name+' / '+p.team})),preferred||$('player').value,false);
    const pitcher=$('role').value==='pitcher';
    options('hand',pitcher?['右打','左打','両打']:['右投','左投']);
  }
  async function loadPlayer(preferredFilters){
    const token=++loadToken;playerData=null;dirty();$('compare').disabled=true;
    const id=$('player').value;
    if(!id){message('条件に一致する選手がいません。検索条件を変更してください。');return;}
    try {
      const raw=await json(base+encodeURIComponent(id)+'.json');
      if(token!==loadToken)return;
      playerData=M.decode(raw);
      for(const [id,key] of [['type','pitch_type'],['count','count_before'],['zone','zone_label']])options(id,[...new Set(playerData.pitches.map(p=>p[key]).filter(Boolean))].sort(),preferredFilters?.[id]||'');
      $('compare').disabled=false;
      message('選手データを読み込みました。期間と条件を指定して比較できます。');
    }catch(e){if(token===loadToken)message(e.message+' 選手を選び直すと再試行できます。');}
  }
  function defaults(){const p=manifest.periods;['a0','a1','b0','b1'].forEach((k,i)=>$(k).value=p[i]);}
  function metricCard(title,key,a,b,na,nb,format){const delta=a==null||b==null?null:b-a;const change=delta==null?'—':(delta>0?'+':'')+(key==='speed'?fmt(delta,1)+' km/h':key==='ops'?fmt(delta):fmt(delta*100,1)+' pt');return '<article class="metric"><h3>'+esc(title)+'</h3><div class="value a">'+esc(format(a))+'</div><div class="value b">'+esc(format(b))+'</div><small>A → B / 差 '+esc(change)+'<br>母数 A '+esc(na)+' / B '+esc(nb)+'</small><button data-metric="'+key+'">根拠の打席を見る</button></article>';}
  function distribution(id,a,b){const keys=[...new Set([...Object.keys(a),...Object.keys(b)])].sort((x,y)=>(b[y]||0)+(a[y]||0)-(b[x]||0)-(a[x]||0));const na=Object.values(a).reduce((x,y)=>x+y,0),nb=Object.values(b).reduce((x,y)=>x+y,0);$(id).innerHTML=keys.map(k=>'<div class="bars"><b>'+esc(k)+'</b>'+[[a,na,'A','a'],[b,nb,'B','b']].map(([c,n,label,cl])=>'<div class="bar-line"><span>'+label+'</span><div class="track"><div class="fill '+cl+'" style="width:'+(n?100*(c[k]||0)/n:0)+'%"></div></div><span>'+pct(n?(c[k]||0)/n:null)+' / '+(c[k]||0)+'球</span></div>').join('')+'</div>').join('')||'<p class="empty">取得済みデータがありません。</p>';}
  function quality(){const a=result.sa,b=result.sb;const interval=x=>x?x.map(pct).join(' 〜 '):'算出不可';const rows=[['対象試合',a.games,b.games],['対象打席',a.pa,b.pa],['OPS算出可能打席',a.complete_pa,b.complete_pa],['対象投球',a.pitches,b.pitches],...['speed','zone','result','type'].map((k,i)=>[['球速取得率','コース取得率','スイング結果取得率','球種取得率'][i],pct(a.pitches?a.quality[k]/a.pitches:null),pct(b.pitches?b.quality[k]/b.pitches:null)]),['空振り率 95%区間',interval(a.whiff_ci),interval(b.whiff_ci)],['ボール球スイング率 95%区間',interval(a.chase_ci),interval(b.chase_ci)]];
    $('quality').innerHTML=(a.pa<50||b.pa<50?'<p class="flag">いずれかの期間が50打席未満です。少数の結果で大きく変動します。</p>':'')+(a.pa!==a.complete_pa||b.pa!==b.complete_pa?'<p class="flag">成績項目に欠損のある打席はOPSの計算から除外しました。</p>':'')+table(['項目','期間A','期間B'],rows.map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>'));
  }
  function renderSequences(){const a=new Map(result.seqA.map(t=>[t.label,t])),b=new Map(result.seqB.map(t=>[t.label,t]));const labels=[...new Set([...a.keys(),...b.keys()])].sort((x,y)=>(b.get(y)?.n||0)+(a.get(y)?.n||0)-(b.get(x)?.n||0)-(a.get(x)?.n||0));
    $('sequences').innerHTML=labels.length?table(['前球の球種 → コース → 次球','A 球数 / 空振り率 (スイング数)','B 球数 / 空振り率 (スイング数)','根拠'],labels.slice(0,sequenceLimit).map(label=>{const x=a.get(label),y=b.get(label);return '<tr><td>'+esc(label)+'</td><td>'+(x?x.n+' / '+pct(x.whiff)+' ('+x.swings+')':'0 / —')+'</td><td>'+(y?y.n+' / '+pct(y.whiff)+' ('+y.swings+')':'0 / —')+'</td><td><button data-sequence="'+esc(label)+'">対象打席</button></td></tr>';})):'<p class="empty">条件に一致する連続2球がありません。</p>';
    $('more-sequences').hidden=labels.length<=sequenceLimit;
    $('sequences').querySelectorAll('[data-sequence]').forEach(btn=>btn.onclick=()=>{const label=btn.dataset.sequence;setEvidence(label,c=>new Set((c==='A'?a:b).get(label)?.refs||[]));});
  }
  function setEvidence(label,keysForPeriod){evidenceLabel=label;evidenceLimit=30;evidenceRows=[];for(const [period,c] of [['A',result.a],['B',result.b]]){const keys=keysForPeriod?keysForPeriod(period):null;c.atbats.filter(r=>!keys||keys.has(M.key(r))).forEach(r=>evidenceRows.push({...r,period}));}evidenceRows.sort((a,b)=>b.date.localeCompare(a.date)||a.atbat_index.localeCompare(b.atbat_index));renderEvidence();}
  function renderEvidence(){$('evidence-caption').textContent=evidenceLabel+' / '+evidenceRows.length+'打席（表示 '+Math.min(evidenceLimit,evidenceRows.length)+'件）';$('evidence').innerHTML=evidenceRows.length?table(['期間','日付','打者','投手','結果','リプレイ'],evidenceRows.slice(0,evidenceLimit).map(r=>'<tr><td>'+r.period+'</td><td>'+esc(r.date)+'</td><td>'+esc(r.batter)+'</td><td>'+esc(r.pitcher)+'</td><td>'+esc(r.result)+'</td><td>'+(M.replay(r)?'<a href="'+esc(M.replay(r))+'" target="_blank" rel="noopener">この打席を見る ↗</a>':'リンク情報なし')+'</td></tr>')):'<p class="empty">対象打席がありません。</p>';$('more-evidence').hidden=evidenceRows.length<=evidenceLimit;}
  function metricEvidence(metric){const predicate={speed:p=>p.pitch_type==='ストレート'&&typeof p.speed_kmh==='number'&&p.speed_kmh>0,whiff:p=>p.is_swing===true&&typeof p.is_miss==='boolean',chase:p=>p.in_zone===false&&typeof p.is_swing==='boolean'}[metric];setEvidence({speed:'直球球速の集計対象',whiff:'空振り率の集計対象',chase:'ボール球スイング率の集計対象',ops:'OPSの集計対象'}[metric],period=>{const c=period==='A'?result.a:result.b;if(predicate)return new Set(c.pitches.filter(predicate).map(M.key));return new Set(c.atbats.filter(r=>['ab','hit','single','double','triple','hr','bb','hbp','sf'].every(f=>typeof r[f]==='number'&&Number.isFinite(r[f]))).map(M.key));});$('evidence-panel').scrollIntoView({block:'start'});}
  function context(){return 'A '+applied.a0+' 〜 '+applied.a1+' / B '+applied.b0+' 〜 '+applied.b1+' / '+[applied.hand||'左右すべて',applied.risp==='yes'?'得点圏':applied.risp==='no'?'非得点圏':'走者すべて',applied.type||'全球種',applied.count||'全カウント',applied.zone||'全コース'].join('・');}
  function run(){try{if(!playerData)throw new Error('選手データを読み込んでから比較してください。');const s=snapshot();result=M.compare(playerData,s);applied=s;const a=result.sa,b=result.sb;$('results').hidden=false;$('result-title').textContent=playerData.player.name+' / '+(s.role==='pitcher'?'投手分析':'打者分析');$('result-context').textContent=context();$('metrics').innerHTML=metricCard(s.role==='pitcher'?'被OPS':'OPS','ops',a.ops,b.ops,a.complete_pa+'打席',b.complete_pa+'打席',v=>fmt(v))+metricCard('空振り率 / スイング','whiff',a.whiff,b.whiff,a.swings+'回',b.swings+'回',pct)+metricCard('ボール球スイング率','chase',a.chase,b.chase,a.outside+'球',b.outside+'球',pct)+metricCard('直球平均球速 km/h','speed',a.speed,b.speed,a.speed_n+'球',b.speed_n+'球',v=>fmt(v,1));$('metrics').querySelectorAll('[data-metric]').forEach(b=>b.onclick=()=>metricEvidence(b.dataset.metric));distribution('mix',a.types,b.types);distribution('zones',a.zones,b.zones);quality();sequenceLimit=30;renderSequences();setEvidence('すべての対象打席');message(a.pa&&b.pa?'比較を更新しました。':'一方または両方の期間に対象打席がありません。期間・条件を確認してください。');}catch(e){$('results').hidden=true;result=null;message(e.message);}}
  function savedOptions(selected=''){options('saved',presets.map((p,i)=>({value:String(i),label:p.name})),selected,false);if(!presets.length)$('saved').append(new Option('保存した条件はありません',''));}
  function persist(){try{localStorage.setItem(storageKey,JSON.stringify(presets));savedOptions();message('このブラウザに保存しました。');return true;}catch(e){message('ブラウザの保存領域が利用できません。条件は保存できませんでした。');return false;}}
  async function restore(s){if(!s||!manifest.players.some(p=>p.id===s.player&&p.role===s.role)){message('保存した選手は現在のデータにありません。');return;}$('role').value=s.role;$('search').value='';populatePlayers(s.player);for(const f of ['hand','risp','a0','a1','b0','b1'])$(f).value=s[f]||'';await loadPlayer(s);if(playerData){const dropped=['type','count','zone'].some(f=>(s[f]||'')!==$(f).value);run();if(dropped)message('現在のデータにない投球条件を「すべて」に変更しました。条件を確認してください。');}}
  function renderAlerts(){const rows=manifest.alerts.filter(a=>!$('alert-role').value||a.role===$('alert-role').value);$('alert-count').textContent='('+rows.length+'件)';$('alert-list').innerHTML=rows.length?table(['選手','役割','変化','A → B','母数 A / B','比較'],rows.slice(0,alertLimit).map(a=>'<tr><td>'+esc(a.name)+'</td><td>'+(a.role==='pitcher'?'投手':'打者')+'</td><td>'+esc(a.metric)+'</td><td>'+esc(a.unit==='rate'?pct(a.before)+' → '+pct(a.after):fmt(a.before,1)+' → '+fmt(a.after,1)+' km/h')+'</td><td>'+a.n_a+' / '+a.n_b+'</td><td><button data-alert="'+esc(a.player)+'">比較を開く</button></td></tr>')):'<p class="empty">基準を満たす変化候補はありません。</p>';$('more-alerts').hidden=rows.length<=alertLimit;$('alert-list').querySelectorAll('[data-alert]').forEach(b=>b.onclick=async()=>{const p=manifest.players.find(p=>p.id===b.dataset.alert);await restore({role:p.role,player:p.id,...Object.fromEntries(['a0','a1','b0','b1'].map((k,i)=>[k,manifest.periods[i]]))});$('filters').scrollIntoView({block:'start'});});}
  function download(blob,name){const url=URL.createObjectURL(blob);if(name.endsWith('.png')){const img=$('preview-image');if(img.dataset.url)URL.revokeObjectURL(img.dataset.url);img.src=url;img.dataset.url=url;$('preview-download').href=url;$('preview-download').download=name;$('card-preview').showModal();return;}const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  function note(){const a=result.sa,b=result.sb;return '# '+playerData.player.name+' 期間比較\n\n'+context()+'\n\nデータ基準日: '+manifest.data_date+'\n\n| 指標 | A | B |\n|---|---:|---:|\n'+[['対象打席',a.pa,b.pa],['対象投球',a.pitches,b.pitches],[applied.role==='pitcher'?'被OPS':'OPS',fmt(a.ops),fmt(b.ops)],['空振り率',pct(a.whiff),pct(b.whiff)],['スイング母数',a.swings,b.swings],['ボール球スイング率',pct(a.chase),pct(b.chase)],['直球平均km/h',fmt(a.speed,1),fmt(b.speed,1)],['直球球速母数',a.speed_n,b.speed_n]].map(r=>'| '+r.join(' | ')+' |').join('\n')+'\n\n## 分析の確かさ\n\n'+$('quality').innerText+'\n\n## 解釈上の限界\n\n取得済みデータのみ。相手・球場・役割は未調整。相関から因果や投球意図を断定しない。球種・カウント・コース指定時のOPSは該当球を含む打席の最終結果。\n\n## 根拠の打席（現在の絞り込み、先頭30件）\n\n'+evidenceRows.slice(0,30).map(r=>'- '+r.period+' '+r.date+' '+r.batter+' vs '+r.pitcher+' / '+r.result+(M.replay(r)?' / '+new URL(M.replay(r),location.href).href:'')).join('\n')+'\n';}
  async function card(){if(!result)return;try{if(document.fonts)await document.fonts.ready;const canvas=document.createElement('canvas');canvas.width=1400;canvas.height=1100;const c=canvas.getContext('2d');c.fillStyle='#f3f5f8';c.fillRect(0,0,1400,1100);const text=(s,x,y,size=20,color='#182a3f')=>{c.fillStyle=color;c.font='600 '+size+'px system-ui, sans-serif';c.fillText(s,x,y);};text('NPB  /  ANALYSIS WORKBENCH',60,65,18,'#57718a');text(playerData.player.name+' 期間比較',60,128,42);text('A '+applied.a0+' 〜 '+applied.a1,60,177,21,'#2264b0');text('B '+applied.b0+' 〜 '+applied.b1,710,177,21,'#b94e16');const filterText=[applied.role==='pitcher'?'投手':'打者',applied.hand||'左右すべて',applied.risp==='yes'?'得点圏':applied.risp==='no'?'非得点圏':'走者すべて',applied.type||'全球種',applied.count||'全カウント',applied.zone||'全コース'].join(' / ');text(filterText,60,218,18);const a=result.sa,b=result.sb;const metrics=[[applied.role==='pitcher'?'被OPS':'OPS',fmt(a.ops),fmt(b.ops),a.complete_pa+' / '+b.complete_pa+' 打席'],['空振り率',pct(a.whiff),pct(b.whiff),a.swings+' / '+b.swings+' スイング'],['ボール球スイング率',pct(a.chase),pct(b.chase),a.outside+' / '+b.outside+' 球'],['直球平均 km/h',fmt(a.speed,1),fmt(b.speed,1),a.speed_n+' / '+b.speed_n+' 球']];metrics.forEach((m,i)=>{const x=60+i*325;c.fillStyle='white';c.fillRect(x,250,305,185);text(m[0],x+18,282,19);text(m[1],x+18,337,36,'#2264b0');text(m[2],x+160,337,36,'#b94e16');text('母数 A / B',x+18,378,14);text(m[3],x+18,410,17);});text('球種割合の比較（上位5球種）',60,486,24);const na=Object.values(a.types).reduce((n,v)=>n+v,0),nb=Object.values(b.types).reduce((n,v)=>n+v,0);const kinds=[...new Set([...Object.keys(a.types),...Object.keys(b.types)])].sort((x,y)=>(b.types[y]||0)+(a.types[y]||0)-(b.types[x]||0)-(a.types[x]||0)).slice(0,5);kinds.forEach((k,i)=>{const y=535+i*68;text(k,60,y+12,18);for(const [j,types,n,color] of [[0,a.types,na,'#2264b0'],[1,b.types,nb,'#b94e16']]){const rate=n?(types[k]||0)/n:null;c.fillStyle=color;c.fillRect(300,y-8+j*22,(rate||0)*780,14);text(pct(rate)+' ('+(types[k]||0)+'球)',1120,y+5+j*22,16,color);}});if(!kinds.length)text('球種データなし',60,545,20);text('対象：A '+a.pa+'打席 / '+a.pitches+'球　 B '+b.pa+'打席 / '+b.pitches+'球',60,905,20);text('空振り率95%参考区間 A '+(a.whiff_ci?a.whiff_ci.map(pct).join('–'):'算出不可')+' / B '+(b.whiff_ci?b.whiff_ci.map(pct).join('–'):'算出不可'),60,943,18);text('取得済みデータのみ・相手/球場未調整・因果関係を示さない・区間は投球の依存を未調整',60,985,17);text('条件指定時のOPS：該当球を含む打席の最終結果。詳細な取得率・根拠はMarkdownへ。',60,1018,17);text('データ基準日 '+manifest.data_date+'  /  出典：リポジトリ内の収集データ',60,1061,17,'#57718a');canvas.toBlob(blob=>{if(blob){download(blob,'npb-comparison-'+manifest.data_date+'.png');message('分析カードを生成しました。プレビューからPNGを保存できます。');}else message('画像の生成に失敗しました。');},'image/png');}catch(e){message('画像を生成できませんでした：'+e.message);}}
  $('filters').onsubmit=e=>{e.preventDefault();run();};
  $('role').onchange=()=>{populatePlayers();loadPlayer();};$('search').oninput=()=>{populatePlayers();loadPlayer();};$('player').onchange=()=>loadPlayer();
  fields.filter(f=>!['role','player'].includes(f)).forEach(f=>$(f).onchange=dirty);
  $('reset').onclick=()=>{defaults();['hand','risp','type','count','zone'].forEach(f=>$(f).value='');dirty();};
  $('save').onclick=()=>{const s=snapshot(),error=M.validate(s);if(error){message(error);return;}if(!s.player){message('選手を選んでください。');return;}const name=$('save-name').value.trim();if(!name){message('保存名を入力してください。');$('save-name').focus();return;}if(presets.length>=50){message('保存は50件までです。不要な条件を削除してください。');return;}const old=presets.slice();presets.push({name,state:s});if(!persist())presets=old;};
  $('restore').onclick=()=>{const p=presets[Number($('saved').value)];if(p)restore(p.state);};$('remove').onclick=()=>{if($('saved').value==='')return;const old=presets.slice();presets.splice(Number($('saved').value),1);if(!persist())presets=old;};
  $('alert-role').onchange=()=>{alertLimit=30;renderAlerts();};$('more-alerts').onclick=()=>{alertLimit+=30;renderAlerts();};$('more-sequences').onclick=()=>{sequenceLimit+=30;renderSequences();};$('more-evidence').onclick=()=>{evidenceLimit+=30;renderEvidence();};$('clear-evidence').onclick=()=>setEvidence('すべての対象打席');
  $('card').onclick=card;$('markdown').onclick=()=>{if(result)download(new Blob([note()],{type:'text/markdown;charset=utf-8'}),'npb-analysis-'+manifest.data_date+'.md');};
  $('compare').disabled=true;
  $('close-preview').onclick=()=>$('card-preview').close();
  json(base+'index.json').then(async data=>{manifest=data;$('status').textContent=data.first_date+' 〜 '+data.data_date+' / '+data.players.length+'選手・役割';defaults();populatePlayers();renderAlerts();try{const saved=JSON.parse(localStorage.getItem(storageKey)||'[]');presets=Array.isArray(saved)?saved.filter(p=>typeof p.name==='string'&&p.state&&typeof p.state==='object').slice(0,50):[];}catch(e){presets=[];}savedOptions();await loadPlayer();if(playerData)run();}).catch(e=>{$('status').textContent='データを読み込めません';message(e.message+' ページを再読み込みしてください。');});
})();
